### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by asksmruti** [auchanretailfrance/nexus3-gitlabauth-plugin#7]
I was trying to setup gitlabauth plugin, however it's complaining with authentication failure - 

On UI -  Incorrect username or password, or no permission to use the application.
In the log file, no genuine message to understand why it's failing - 

`2021-05-14 11:07:50,905+0200 INFO  [qtp624719531-45]  *UNKNOWN fr.auchan.nexus3.gitlabauth.plugin.GitlabAuthenticatingRealm - doGetAuthenticationInfo for xxxxx`

I am using the gitlab user name and personal token to authenticate. same token works well with `curl`

**Comment by asksmruti** [comment]
It's working fine. All good.

**Comment by a-savinov** [comment]
> 

Hi, I have the same error 
Can you tell me how you fixed it ?
